Joelhanson/appfour/urls.py
from django.conf.urls import url
from . import views

app_name = 'appfour'

urlpatterns = [
    url(r'^$',views.IndexView.as_view(),name="index"),
    url(r'^register/',views.register,name="register"),
	url(r'^(?P<pk>\d+)/$',views.IndexView.as_view(),name='detail'),
	url(r'^list/',views.TravelListView.as_view(),name='list'),


]

Joelhanson/profour/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from appfour import views
from django.contrib.auth import views #importing some views from the authorization app
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'',include('appfour.urls')),
	url(r'^accounts/login/$', views.login, name='login'),
    url(r'^accounts/logout/$', views.logout, name='logout', kwargs={'next_page':'/'}),
    url(r'^accounts/profile/',include('appfour.urls')),
]

Joelhanson/appfour/models.py
from django.db import models
# from django.utils import timezone
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse
from datetime import date
# Create your models here.

class UserProfileInfo(models.Model):
	user = models.OneToOneField(User)
	TRAVELMATE_SOLUTION = 'Travelmate Solutons'
	TRAVIDUX_TECHNOLOGIES = 'Travidux Technologies'
	department = (
	(TRAVELMATE_SOLUTION, 'Travelmate Solutons'),
	(TRAVIDUX_TECHNOLOGIES, 'Travidux Technologies'),
	)
	department = models.CharField(
	max_length=21,
	choices=department,
	default=TRAVELMATE_SOLUTION,
	)
	password = models.CharField(max_length=30,null=True)
	confirm_password = models.CharField(max_length=30,null=True)
	def __str__(self):
		return self.user.email


class TravelDetails(models.Model):

	author = models.ForeignKey(User,unique=False)
	origin = models.CharField(max_length=200,null=False)
	desitination = models.CharField(max_length=200,null=False)
	paxname = models.CharField(max_length=200,null=True)
	amount = models.FloatField(null=True)
	# details = models.CharField(max_length=200,null=True)
	created_date = models.DateTimeField(default=date.today)

	# def get_absolute_url(self):
    #     return reverse("report", kwargs={'pk':self.pk})

	def __str__(self):
		return str(self.author)

Joelhanson/appfour/forms.py
from django import forms
from django.contrib.auth.models import User
from appfour.models import UserProfileInfo,TravelDetails

class UserForm(forms.ModelForm):
	class Meta():
		model = User
		fields = ('first_name','last_name','email','username')
		widgets = {
		# The class here is a CSS class.
		'first_name' : forms.TextInput(attrs={'class':'form-control'}),
		'last_name' : forms.TextInput(attrs={'class':'form-control'}),
		'email' : forms.TextInput(attrs={'class':'form-control'}),
		'username' : forms.TextInput(attrs={'class':'form-control'}),
		}

class UserProfileInfoForm(forms.ModelForm):
	password = forms.CharField(widget=forms.PasswordInput)
	confirm_password = forms.CharField(widget=forms.PasswordInput)
	class Meta():
		model = UserProfileInfo
		fields = ('password','confirm_password','department',)
		widgets = {
		# The class here is a CSS class.
		# 'password':forms.CharField(attrs={'class':'form-control'}),
		# 'confirm_password':forms.CharField(attrs={'class':'form-control'}),
		'department' : forms.Select(attrs={'class':'form-control'}),
		}
	def clean(self):
		cleaned_data = super(UserProfileInfoForm, self).clean()
		password = cleaned_data.get("password")
		confirm_password = cleaned_data.get("confirm_password")
		if password != confirm_password:
		 raise forms.ValidationError(
		 "password and confirm_password does not match"
		 )

class TravelDetailsForm(forms.ModelForm):
	# created_date = forms.DateField(widget=forms.DateInput)
	class Meta():
		model = TravelDetails
		fields =  ('origin','desitination','paxname','amount','created_date')

Joelhanson/appfour/views.py
from django.shortcuts import render,HttpResponseRedirect
from appfour.forms import UserProfileInfoForm,UserForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import (TemplateView, ListView,
                                    DetailView, CreateView,
                                    UpdateView, DeleteView,FormView)
from appfour.models import TravelDetails
from appfour.forms import TravelDetailsForm


# Create your views here.


class IndexView(LoginRequiredMixin,CreateView):
	login_url = 'login' # if this person is not logged in, where should this person go? To login_url
	context_object_name = 'form'
	model = TravelDetails
	fields = ('origin','desitination','paxname','amount','created_date')
	template_name = 'appfour/travel_insert.html'
	success_url = 'list'
	def form_valid(self, form):
		self.object = form.save(commit=False)
		self.object.author = self.request.user
		self.object.save()
		return super().form_valid(form)



class TravelListView(LoginRequiredMixin,ListView):
	login_url = 'login' # if this person is not logged in, where should this person go? To login_url
	context_object_name = 'form'
	model = TravelDetails
	template_name = 'appfour/travel_list.html'

def register(request):
	registered = False
	if request.method == "POST":
		user_form = UserForm(data = request.POST)
		profile_form = UserProfileInfoForm(data = request.POST)
		if user_form.is_valid() and profile_form.is_valid():
			user = user_form.save()
			profile = profile_form.save(commit = False)
			user.set_password(profile.password)
			user.save()
			profile.user = user
			profile.save()
			registered = True
		else:
			print(user_form.errors,profile_form.errors)
	else:
		user_form = UserForm()
		profile_form = UserProfileInfoForm()
		print("Not POST")
	return render(request,'appfour/register.html',{'user_form':user_form,'profile_form':profile_form,'registered':registered})
#
# class ReportListView(LoginRequiredMixin,ListView):
# 	login_url = '/login/'
#     # redirect_field_name = 'appfour/repost.html'
# 	template_name = 'appfour/repost.html'
#     model = TravelDetails

Joelhanson/appfour/templates/appfour/appfour_base.html
<!doctype html> {% load staticfiles %}
<html lang="en">

<head>
	<title>Hello, world!</title>
	<!-- Required meta tags -->
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

	<!-- Bootstrap CSS -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">
	<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
	<link href="{% static "css/autocomplete.min.css" %}" rel="stylesheet">

</head>
<style media="screen">
	body {
		background-color: #e9ecef;
	}
</style>

<body>
	<nav class="navbar navbar-expand-lg navbar-light bg-light rounded">
		<a class="navbar-brand" href="/">Home</a>
		<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
		    <span class="navbar-toggler-icon"></span>
		  </button>

		<div class="collapse navbar-collapse" id="navbarSupportedContent">
			<ul class="navbar-nav mr-auto">
				<li class="nav-item ">
					<a class="nav-link" href="{% url 'appfour:register' %}">Register</a>
				</li>

				<li class="nav-item">
					<a class="nav-link" href="{% url 'admin:index'%}">Admin</a>
				</li>


			</ul>
			<ul class="navbar-nav ml-auto">
				{% if user.is_authenticated %}
				<li class="nav-item nav-right">
					<a class="nav-link" href="{% url 'appfour:list'%}">Report</a>
				</li>
				<li class="nav-item">
					<a class="nav-link" href="{% url 'logout'%}">logout</a>
				</li>

				{% else %}
				<li class="nav-item">
					<a class="nav-link" href="{% url 'login'%}">login</a>
				</li>
				{% endif %}
			</ul>
		</div>
	</nav>

	<div class="jumbotron">
		<div class="container" style="text-align:center;">

			{% block content %} {% endblock %}
		</div>

	</div>

	<!-- Optional JavaScript -->
	<!-- jQuery first, then Popper.js, then Bootstrap JS -->
	<!-- <script src="https://code.jquery.com/jquery-1.5.js" integrity="sha256-NhPIl0e+Si1dwX9ELQpILaZleE4uWjkx+5ofw4+g+o0=" crossorigin="anonymous"></script> -->
	<script src="https://code.jquery.com/jquery-3.2.1.js" integrity="sha256-DZAnKJ/6XZ9si04Hgrsxu/8s717jcIzLy3oi35EouyE=" crossorigin="anonymous"></script>
	<!-- <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script> -->
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script>
</body>

</html>

Joelhanson/appfour/templates/appfour/travel_list.html
{% extends "appfour/appfour_base.html"%} {% block content %}
{% load staticfiles %}
<div class="d-flex justify-content-center">
	<div class="row">

	{% for f in form %}



	{% if f.author == request.user %}


	<div class="col-12 d-flex justify-content-center">
	<div class="card border-primary mb-3" style="width: 20rem;">
  <div class="card-header">{{f.created_date}}</div>
  <div class="card-body ">
		<div class="row">
			<div class="col-5">
				{{f.origin}}
			</div>
			<div class="card-title col-2">
			<img src="{% static 'images/arrow.svg' %}" alt="">
			</div>
			<div class="card-title col-5">
				{{f.desitination}}
			</div>
		</div>
		<h5  class="card-text">paxname: {{f.paxname}} </h5>
		<h5 class="card-text">Amount: {{f.amount}}</h5>
  </div>
</div>
</div>
{% endif %}
{% endfor %}
</div>

</div>


 {% endblock %}

Joelhanson/templates/appfour/base.html
<!doctype html> {% load staticfiles %}
<html lang="en">

<head>
	<title>Hello, world!</title>
	<!-- Required meta tags -->
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

	<!-- Bootstrap CSS -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">
	<style media="screen">
		body {
			background-color: #e9ecef;
		}
	</style>
</head>

<body>
	<nav class="navbar navbar-expand-lg navbar-light bg-light rounded">
		<a class="navbar-brand" href="/">Home</a>
		<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
		    <span class="navbar-toggler-icon"></span>
		  </button>

		<div class="collapse navbar-collapse" id="navbarSupportedContent">
			<ul class="navbar-nav mr-auto">
				<li class="nav-item ">
					<a class="nav-link" href="{% url 'appfour:register' %}">Register</a>
				</li>

				<li class="nav-item">
					<a class="nav-link" href="{% url 'admin:index'%}">Admin</a>
				</li>


			</ul>
			<ul class="navbar-nav ml-auto">
				{% if user.is_authenticated %}
				<li class="nav-item">
					<a class="nav-link" href="{% url 'logout'%}">logout</a>
				</li>
				<li class="nav-item nav-right">
					<a class="nav-link" href="{% url 'appfour:list'%}">Report</a>
				</li>
				{% else %}
				<li class="nav-item">
					<a class="nav-link" href="{% url 'login'%}">login</a>
				</li>
				{% endif %}
			</ul>
		</div>
	</nav>

	<div>
		<div class="container" style="text-align:center;">
			{% block content %} {% endblock %}
		</div>

	</div>

	<!-- Optional JavaScript -->
	<!-- jQuery first, then Popper.js, then Bootstrap JS -->
	<script src="https://code.jquery.com/jquery-3.2.1.js" integrity="sha256-DZAnKJ/6XZ9si04Hgrsxu/8s717jcIzLy3oi35EouyE=" crossorigin="anonymous"></script>
	<!-- <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script> -->
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script>
</body>

</html>

Joelhanson/templates/appfour/index.html
<!DOCTYPE html> {% extends "appfour/base.html" %} {% block content %} {% if user.is_authenticated %}
{% load staticfiles %}




		</div>
	</div>


</div>
{% else %}
<div>
	<h1>You are not logged in</h1>
</div>
{% endif %} {% endblock %}

Joelhanson/templates/appfour/register.html
<!DOCTYPE html> {% extends "appfour/base.html" %} {% load staticfiles %} {% block content %}
{% load appfour_extras %}

<div>
	<h1 style="margin:30px;">Registration Test</h1>
	<br> {% if registered %}
	<h1>Registered</h1>
	<br> {% else %}
	<br>
	<form enctype="multipart/form-data" method="post" class="d-flex justify-content-center" style="margin:0 30px 30px 30px;">
		{% csrf_token %}
		<div class="card text-center" style="width: 30rem;">
			<div class="card-header">
				<h4>Register Here</h4>
			</div>
			<div class="card-block" style="margin:30px">
				{{ user_form.non_field_errors }}
				<div class="form-group row">
					{{ user_form.first_name.errors }}
					<label for="{{ user_form.first_name.id_for_label }}">First Name: </label> {{ user_form.first_name}}
				</div>
				<div class="form-group row">
					{{ user_form.last_name.errors }}
					<label for="{{ user_form.last_name.id_for_label }}">Last Name: </label> {{ user_form.last_name }}
				</div>
				<div class="form-group row">
					{{ user_form.email.errors }}
					<label for="{{ user_form.email.id_for_label }}">Your email address:</label> {{ user_form.email }}
					<small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
				</div>
				<div class="form-group row">
					{{ user_form.username.errors }}
					<label for="{{ user_form.username.id_for_label }}">Username :</label> {{ user_form.username }}
					<small id="emailHelp" class="form-text text-muted">We'll never share your username with anyone else.</small>
				</div>
				<div class="form-group row">
					{{ profile_form.password.errors }}
					<label for="{{ profile_form.password.id_for_label }}">Password: </label> {{ profile_form.password|addcss:"form-control" }}
				</div>
					<div class="form-group row">
						{{ profile_form.confirm_password.errors }}
						<label for="{{ profile_form.confirm_password.id_for_label }}">Confirm Password: </label> {{ profile_form.confirm_password|addcss:"form-control" }}
					</div>
					{{ profile_form.department.errors }}
					<div class="form-group row">
						<label for="{{ profile_form.department.id_for_label }}">Department: </label>{{ profile_form.department}}
					</div>
					{{ profile_form.non_field_errors }}
					{{ user_form.non_field_errors }}
					<input type="submit" class="btn btn-primary" name="" value="Register">


		</div>
	</form>
	{% endif %}
</div>
{% endblock %}